FromDoppler/emms21

- admin21/index.php
- config.php
- db.php
feat: add basic admin scaffolder with connection db && config file
> DS-2682_admin_module

- .docker/.env
- .docker/config/nginx/Dockerfile
- .docker/config/nginx/default.conf
- .docker/config/php/Dockerfile
- .docker/config/php/php.conf.ini
- .docker/docker-compose.yml
- .docker/readme.md
- .gitignore
> DS-2727_dockerization

- 404.php
- css/styles.css
> DS-2715-page-404

- css/styles.css
- index-second-state.html
- js/timer.js
feature: add index second state
> DS-2704-index-second-state

- config.php
- index.php
- js/registrarEmms.js
- services/curl.php
- services/registrarEmms.php
- services/success-reservation.php
- services/utils/SecurityHelper.php
- services/utils/getIpAddress.php
feat: add initial registration flow
> DS-2691_registrar_emms

- .docker/db/EMMS21.sql
> feat: script db init

- css/styles.css
- index-third-state.html
feature: add index third state
> DS-2704-third-state

- css/styles.css
- index.php
- nav.js
> DS-2703-add-navbar

- .docker/db/EMMS21.sql
- config.php
- services/insertarEnSuscriptionsDoppler.php
- services/registrarEmms.php
Ds 2760 create service save subscriptions doppler
Submit
bd
> DS-2760-create-service-save-suscrptions_doppler

- .docker/db/EMMS21.sql
- services/insertarEnRegistrados.php
- services/registrarEmms.php
Ds 2691 create service save registrados
si el email que submitea no se encuentra en la tabla registrados, lo inserta. Caso contrario realiza la actualización del registro
> DS-2691-create-service-save-registrados

- index.php
- js/registrarEmms.js
- js/validateForm.js
- js/validatePhone.js
feat: add JS form fields validation
> DS-2742_JS_validate_form

- js/registrarEmms.js
fix: remove json response from registrarEmmsFunction.
> fix_response_registrar_emms

- 404.php
- ediciones-anteriores.php
- index.php
> DS-2710-add-favicons

- css/styles.css
- index-first-state.php
- index-second-state.php
- index.php
> DS-2797-fix-css

- .docker/db/EMMS21.sql
- config.php
- services/actualizarRegistrado.php
- services/insertarEnRegistrados.php
- services/invitarContactos.php
- services/registrarEmms.php
Ds 2796 crear servicio invitacion
> DS-2796-crear-servicio-invitacion

- css/styles.css
- index-first-state.php
- index-second-state.php
- index.php
> DS-2797-change-button

- index-second-state.php
- js/firstState.js
- js/modules/validateForm.js
- js/secondState.js
fix: refactor over fetch service call to invite two users
> DS-2692_fix_fetch_service_call

- js/firstState.js
- js/secondState.js
> fix: JS form validations

- services/invitarContactos.php
fix: storage custom fields politica & invito_dos_personas
> fix_service_invitar_contactos_custom_fields

- css/libs/cookies/cookies.css
- index.php
feat: add library cookie consent to show modal RGPD https://www.osano.com/cookieconsent/
> DS-2792_cookie_consent_modal

- services/invitarContactos.php
fix: permite ahora enviar un solo invitado o dos
> DS-2808_permitir_un_solo_invitado

- index-second-state.php
- js/secondState.js
- services/invitarContactos.php
feat: catch from query ulr params utm user data & storage to suscriptions_doppler table
> DS-2830_storage_utm_data_to_invitados_db

- 404.php
- ediciones-anteriores.php
- index-second-state.php
- index-third-state.php
- index.php
feat: allow to add the event to my calendar
> DS-2694-add-to-calendar

- js/firstState.js
- js/statesHandler.js
- services/registrarEmms.php
feat set customfield esVisitante in emms list
> DS-2844_set_esInvitado_in_emms_registrados_list

- js/firstState.js
- js/statesHandler.js
feat: show waiting screen at visitant registred user
> DS-2845_show_waits_creen_after_registration_visitor

- services/invitarContactos.php
fix: invito_dos_personas value not worcking correctly
> DS-2849_fix_invito_dos_personas_storage_attr

- services/invitarContactos.php
fix: now email_anfitrion is not required to send invitations
> DS-2850_fix_not_necesary_email_anfitrion_to_invite_contacts

- js/statesHandler.js
- js/waitingState.js
feat: add countdown timer 1 minute (for testing purpouses) to change status typeuser and show registated & send invitations
> DS-2814_JS_timer_1hs_update_typeUser_vr_to_pr_and_show_send_invitations_page

- css/styles.css
fix: align previous edition anchors
> DS-2857-fix-previous-edition-card

- ediciones-anteriores.php
- index-first-state.php
- index-second-state.php
- index-third-state.php
- index.php
- waiting-list.php
> DS-2847-fix-anchor-navigation

- css/styles.css
fix: adjust speakers cards in mobile
> DS-2858-adjust-speakers-cards

- 404.php
- ediciones-anteriores.php
- index.php
fix: move GTM script at top but after open body tag
> DS-2821_move_body_script

- admin21/Suscriptores.php
- admin21/report.php
feature - agregar script para generar listado de suscriptores en formato csv
> DS-2879-permitir-descargar-reporte-de-Suscriptores-en-formato.csv

- js/waitingState.js
DS-2884
feat: hide countdown in waitingState & extends 1hs
> feat: hide countdown in waitingState & extends 1hs

- app/1.0.0/css/styles.css
- index-live-state.php
> DS-2906-responsive-styles

- app/1.0.0/css/styles.css
- index.php
fix: fix position with press 'agenda' in nav
> DS-2923-fix-nav-schedule

- index-first-state.php
- index.php
> DS-2932-change-ES-hour

- .docker/db/EMMS21.sql
- admin21/css/admin.css
- admin21/index.php
- admin21/settings.php
- config.php
- index-live-state.php
> Ds 2898 add fields to admin

- app/1.0.0/js/statesHandler.js
it only shows a 10 second wait screen to users with no parameter.
> Ds 2936 fix state waiting 10 seconds when user have param

- app/1.0.0/js/statesHandler.js
- app/1.0.0/js/waitingLiveState.js
- app/1.0.0/js/waitingState.js
- index-live-waiting-state.php
feat. reload screen after 10 seconds
https://www.screencast.com/t/J8pYYFpIhhA
> DS-2931-logic-countdown-10-seconds

- app/1.0.0/css/styles.css
- app/1.0.0/js/statesHandler.js
fix: delete footer in live state
> DS-2935_livestate_delete_footer

- app/1.0.0/css/styles.css
- index-live-state.php
- technical-problems.php
feat: add technical problems template
> DS-2946_template-probleas-tecnicos

- .docker/db/EMMS21.sql
- admin21/css/admin.css
- admin21/index.php
- admin21/simulator.php
- services/getEstado.php
> Ds 2896 simulator intances by ip

- admin21/css/admin.css
- admin21/index.php
> fix styles, fix change option

- index-live-state.php
https://www.screencast.com/t/Y6oyLrLc
> muted autoplay for live video

- index-live-state.php
insert iframe twitch only if youtube id is empty
https://www.screencast.com/t/hwvpQOHq
> DS-2948-iframe-twitch

- app/1.0.0/js/modules/eventStatus.js
- app/1.0.0/js/modules/timer.js
- app/1.0.0/js/statesHandler.js
- config.php
- services/getCounterDates.php
feat: add countdowns eventStatus
> DS-2924_countdown_pre_during

- admin21/settings.php
- app/1.0.0/js/statesHandler.js
screen technical problems
https://www.screencast.com/t/N44C6UFiNbo
> DS-2945-technical-problems

- app/1.0.0/js/statesHandler.js
Feat. Allow change to post state
https://www.screencast.com/t/VlPxbe4e
> DS-2951-change-to-post

- app/1.0.0/js/firstState.js
- app/1.0.0/js/secondState.js
- app/1.0.0/js/statesHandler.js
- app/1.0.0/js/thirdState.js
- app/1.0.0/js/waitingLiveState.js
> DS-2942_fix_delay_functions

- app/1.0.0/js/modules/timer.js
fix: convertion datetime to ml
> DS-2967_ajustar_countdown_visual

- services/getEstado.php
Fix. encode json
https://www.screencast.com/t/IsrKOK08f8o
> DS-2979-fix-simulator

- app/1.0.0/js/firstState.js
> DS-2973-fix-flow-register

- app/1.0.0/js/modules/eventStatus.js
- app/1.0.0/js/modules/timer.js
fix: add timezone ARG in coundown
> fix_timezone_countdown

- app/1.0.0/js/modules/eventStatus.js
- app/1.0.0/js/modules/timer.js
- config.php
fix: timezone to en-us formats & id doppler list test
> fix_timezone_qa_list_dopplerx

- app/1.0.0/css/post/footer.css
- app/1.0.0/css/post/index-post-registered.css
- app/1.0.0/css/post/speaker.css
- app/1.0.0/css/styles.css
- index-post-footer.php
- index-post-state.php
- tim-ash.php
> DS-2912-new-templates

- config.php
feat: add url video speakers in config file
> DS-2957_export_speakers_url_video

- services/getSpeakerUrl.php
feat: add service to get url video from specific speaker
> DS-2957_getSpeakerUrl_service

- app/1.0.0/css/post/speaker.css
- app/1.0.0/css/styles.css
- index.php
feat: change schedule in post event
> DS-2907_change_schedule_post

- app/1.0.0/js/speakerLanding.js
feat: add logic to speakers langing
> DS-2957_create_speaker_landing_logic

- app/1.0.0/js/postState.js
- app/1.0.0/js/speakerLanding.js
- config.php
- elliot-ross.php
- pablo-castellano-alventosa.php
- paola-aldaz-biere.php
- ricardo-diez.php
fix: add correct youtube urls. add change title registered post event. add speaker parameter in div 
current state
> DS-2957_fixes_visual_post_state

- elliot-ross.php
- pablo-castellano-alventosa.php
- paola-aldaz-biere.php
- ricardo-diez.php
- tim-ash.php
> DS-2908_delete_same_speaker

- services/actualizarRegistrado.php
- services/getSubscriptionData.php
- services/registrarEmms.php
fix: refactor registrarEmms service. New function getsubscriptionData to get data api url & list number
> DS-2988_fix_registrarEmms_subscription_data

- app/1.0.0/css/post/speaker.css
feat: align share item in desktop
> DS-2989_align_speakers_share

- elliot-ross.php
- pablo-castellano-alventosa.php
- paola-aldaz-biere.php
- ricardo-diez.php
- tim-ash.php
fix: navigation bar speakers links
> DS-2983_fix_nav_landing_speakers

- app/1.0.0/css/post/speaker.css
feat: change video iframe in tablet
> DS-2990_video_iframe

- app/1.0.0/js/postState.js
- app/1.0.0/js/speakerLanding.js
- index.php
> DS-2984_DS-2986_DS-2987_footer

- app/1.0.0/js/speakerLanding.js
> fix_form_speakers_class

- app/1.0.0/css/post/footer.css
- elliot-ross.php
- pablo-castellano-alventosa.php
- paola-aldaz-biere.php
- ricardo-diez.php
- tim-ash.php
> DS-2978_new_footer

- app/1.0.0/js/firstState.js
- services/actualizarRegistrado.php
- services/enviarEmailRegistro.php
- services/getSubscriptionData.php
- services/invitarContactos.php
- services/registrarEmms.php
Feat. refactoring services by status
> DS-3002-registers-and-list

- app/1.0.0/js/speakerLanding.js
> DS-3006-fix-flow-interna

- sitemap.xml
> DS-3012-updated-sitemap

- app/1.0.0/js/problemsState.js
- app/1.0.0/js/statesHandler.js
feat: automatic refresh from problemsState to normal states
> DS-3014_automatic_refresh_from_problemsState_to_normal_states

- app/1.0.0/js/statesHandler.js
- config.php
- services/getForceRefresh.php
automatic refresh from normal states to problem state
> DS-3014_automatic_refresh_from_normal_states_to_problem_state

- app/1.0.0/js/postState.js
fix: fix changeButton function
> DS-3016-fix

- app/1.0.0/css/styles.css
- index.php
> DS-3004_change_footer

- app/1.0.0/css/post/speaker.css
- config.php
fix: fix iframe preview in mobile
> DS-3054_fix_mobile_iframe

- app/1.0.0/css/popUp.css
- app/1.0.0/js/modules/utm/utm.js
- popUp.php
fix: fix logic in utm
feat: change popUp in desktop
> DS-3212_change_popUp_desktop

- 404.php
- ediciones-anteriores.php
- elliot-ross.php
- index.php
- pablo-castellano-alventosa.php
- paola-aldaz-biere.php
- ricardo-diez.php
- tim-ash.php
> DS-3525_add_ot_in_emms
